=== nathanfdev/deskpro/www/assets/BUILD/pub/src/DeskPRO/Bundle/AgentBundle/Modules/Search/Resources/results_schema.json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties" : false,
  "properties": {
    "organizations": {
      "$id": "/properties/organizations",
      "type": "array",
      "items": {
        "$id": "/properties/organizations/items",
        "type": "object",
        "properties": {
          "id": {
            "$id": "/properties/organizations/items/properties/id",
            "type": "integer",
            "title": "Organization Id",
            "default": 0,
            "examples": [
              1
            ]
          },
          "name": {
            "$id": "/properties/organizations/items/properties/name",
            "type": "string",
            "title": "Organization name",
            "default": "",
            "examples": [
              "Deskpro"
            ]
          },
          "members": {
            "$id": "/properties/organizations/items/properties/members",
            "type": "integer",
            "title": "Number of members of the organization",
            "default": 0,
            "examples": [
              123
            ]
          }
        }
      }
    },
    "people": {
      "$id": "/properties/people",
      "type": "array",
      "items": {
        "$id": "/properties/people/items",
        "type": "object",
        "properties": {
          "id": {
            "$id": "/properties/people/items/properties/id",
            "type": "integer",
            "title": "Person ID",
            "default": 0,
            "examples": [
              1
            ]
          },
          "name": {
            "$id": "/properties/people/items/properties/name",
            "type": "string",
            "title": "Person name",
            "default": "",
            "examples": [
              "Kenneth James"
            ]
          },
          "email": {
            "$id": "/properties/people/items/properties/email",
            "type": "string",
            "title": "Person email",
            "default": "",
            "examples": [
              "raterequests@alllogistics.com"
            ]
          },
          "tickets": {
            "$id": "/properties/people/items/properties/tickets",
            "type": "integer",
            "title": "Number of person tickets",
            "default": 0,
            "examples": [
              132
            ]
          }
        }
      }
    },
    "tickets": {
      "$id": "/properties/tickets",
      "type": "array",
      "items": {
        "$id": "/properties/tickets/items",
        "type": "object",
        "properties": {
          "id": {
            "$id": "/properties/tickets/items/properties/id",
            "type": "integer",
            "title": "Ticket Id",
            "default": 0,
            "examples": [
              83995
            ]
          },
          "subject": {
            "$id": "/properties/tickets/items/properties/subject",
            "type": "string",
            "title": "Ticket subject",
            "default": "",
            "examples": [
              "Pricing and Purchasing Questions"
            ]
          },
          "person_name": {
            "$id": "/properties/people/items/properties/name",
            "type": "string",
            "title": "Person name",
            "default": "",
            "examples": [
              "Kenneth James"
            ]
          },
          "person_email": {
            "$id": "/properties/people/items/properties/email",
            "type": "string",
            "title": "Person email",
            "default": "",
            "examples": [
              "raterequests@alllogistics.com"
            ]
          },
          "agent": {
            "$id": "/properties/tickets/items/properties/agent",
            "type": "integer",
            "title": "Ticket agent Id",
            "default": 0,
            "examples": [
              1
            ]
          },
          "messages": {
            "$id": "/properties/tickets/items/properties/messages",
            "type": "array",
            "items": {
              "$id": "/properties/tickets/items/properties/messages/items",
              "type": "object",
              "properties": {
                "id": {
                  "$id": "/properties/tickets/items/properties/messages/items/properties/id",
                  "type": "integer",
                  "title": "Message Id",
                  "default": 0,
                  "examples": [
                    123
                  ]
                },
                "text": {
                  "$id": "/properties/tickets/items/properties/messages/items/properties/text",
                  "type": "string",
                  "title": "Message text including the searched word including ellipses",
                  "default": "",
                  "examples": [
                    "Many software vendors have government rate pricing that differs from the"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "community": {
      "$id": "/properties/community",
      "type": "array",
      "items": {
        "$id": "/properties/community/items",
        "type": "object",
        "properties": {
          "id": {
            "$id": "/properties/community/items/properties/id",
            "type": "integer",
            "title": "Community Topic Id",
            "default": 0,
            "examples": [
              83995
            ]
          },
          "title": {
            "$id": "/properties/community/items/properties/title",
            "type": "string",
            "title": "Community Topic title",
            "default": "",
            "examples": [
              "Community topic result"
            ]
          }
        }
      }
    },
    "articles": {
      "$id": "/properties/articles",
      "type": "array",
      "items": {
        "$id": "/properties/articles/items",
        "type": "object",
        "properties": {
          "id": {
            "$id": "/properties/articles/items/properties/id",
            "type": "integer",
            "title": "Article Id",
            "default": 0,
            "examples": [
              83995
            ]
          },
          "title": {
            "$id": "/properties/articles/items/properties/title",
            "type": "string",
            "title": "Article title",
            "default": "",
            "examples": [
              "Article result"
            ]
          },
          "status": {
            "$id": "/properties/articles/items/properties/status",
            "type": "string",
            "title": "Article status translated",
            "default": "",
            "examples": [
              "Published"
            ]
          },
          "content": {
            "$id": "/properties/articles/items/properties/content",
            "type": "string",
            "title": "Article content extract with ellipses",
            "default": "",
            "examples": [
              "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
            ]
          }
        }
      }
    },
    "news": {
      "$id": "/properties/news",
      "type": "array",
      "items": {
        "$id": "/properties/news/items",
        "type": "object",
        "properties": {
          "id": {
            "$id": "/properties/news/items/properties/id",
            "type": "integer",
            "title": "News Id",
            "default": 0,
            "examples": [
              83995
            ]
          },
          "title": {
            "$id": "/properties/news/items/properties/title",
            "type": "string",
            "title": "News title",
            "default": "",
            "examples": [
              "News result"
            ]
          }
        }
      }
    },
    "downloads": {
      "$id": "/properties/downloads",
      "type": "array",
      "items": {
        "$id": "/properties/downloads/items",
        "type": "object",
        "properties": {
          "id": {
            "$id": "/properties/downloads/items/properties/id",
            "type": "integer",
            "title": "Download Id",
            "default": 0,
            "examples": [
              83995
            ]
          },
          "title": {
            "$id": "/properties/downloads/items/properties/title",
            "type": "string",
            "title": "Download title",
            "default": "",
            "examples": [
              "Download result"
            ]
          }
        }
      }
    },
    "admin": {
      "$id": "/properties/admin",
      "type": "array",
      "items": {
        "$id": "/properties/admin/items",
        "type": "object",
        "properties": {
          "title": {
            "$id": "/properties/admin/items/properties/title",
            "type": "string",
            "title": "The Title Schema ",
            "default": "",
            "examples": [
              "Admin result"
            ]
          }
        }
      }
    }
  }
}

=== nathanfdev/deskpro/www/assets/BUILD/pub/src/tests/DemoState/AgentBundle/Modules/Search/partial_result.json
{
  "people":[
    {
      "id":1,
      "name":"Kenneth James",
      "email":"raterequests@alllogistics.com",
      "tickets":132
    },
    {
      "id":2,
      "name":"Richard Blaine",
      "email":"hello@email.co.uk",
      "tickets":76
    }
  ],
  "tickets":[
    {
      "id":83995,
      "subject":"Pricing and Purchasing Questions",
      "agent":1,
      "messages":[
        {
          "id":123,
          "text":"Many software vendors have government rate pricing that differs from the"
        }
      ]
    },
    {
      "id":74562,
      "subject":"'Pricing and translations",
      "agent":2,
      "messages":[
        {
          "id":123,
          "text":"...discount policy. The On-Premise pricing is very competitive so it's ..."
        }
      ]
    },
    {
      "id":63331,
      "subject":"ASP Licensing",
      "agent":2,
      "messages":[
        {
          "id":123,
          "text":"if I could make the pricing attractive enough. Several of them are small, and don't ha..."
        }
      ]
    }
  ],
  "community":[
    {
      "id":83995,
      "title":"Community result"
    }
  ],
  "news":[
    {
      "id":83995,
      "title":"News result"
    },
    {
      "id":83996,
      "title":"News result"
    },
    {
      "id":83997,
      "title":"News result"
    }
  ],
  "downloads":[
    {
      "id":83995,
      "title":"Download result"
    }
  ]
}

=== nathanfdev/deskpro/www/assets/BUILD/pub/src/tests/DemoState/AgentBundle/Modules/Search/result.json
{
  "organizations":[
    {
      "id":1,
      "name":"Deskpro",
      "members":123,
      "img": "http://localhost/file.php/avatar/25/default.jpg?size-fit=1"
    },
    {
      "id":2,
      "name":"Deskpro",
      "members":123,
      "img": "http://localhost/file.php/avatar/25/default.jpg?size-fit=1"
    }
  ],
  "people":[
    {
      "id":1,
      "name":"Kenneth James",
      "email":"raterequests@alllogistics.com",
      "tickets":132,
      "img": "http://localhost/file.php/avatar/25/default.jpg?size-fit=1"
    },
    {
      "id":2,
      "name":"Richard Blaine",
      "email":"hello@email.co.uk",
      "tickets":76,
      "img": "http://localhost/file.php/avatar/25/default.jpg?size-fit=1"
    }
  ],
  "tickets":[
    {
      "id":83995,
      "subject":"Pricing and Purchasing Questions",
      "person_name": "Kenneth James",
      "person_email": "kenneth@windfarm.co.uk",
      "agent":1,
      "urgency": 11,
      "messages":[
        {
          "id":123,
          "text":"Many software vendors have government rate pricing that differs from the"
        },
        {
          "id":124,
          "text":"..discount policy. The On-Premise pricing is very competitive so it's ..."
        }
      ]
    },
    {
      "id":74562,
      "subject":"'Pricing and translations",
      "person_name": "Toby Falkirk",
      "person_email": "t.falkirk@rambling.com",
      "agent":2,
      "urgency": 4,
      "messages":[
        {
          "id":123,
          "text":"...discount policy. The On-Premise pricing is very competitive so it's ..."
        }
      ]
    },
    {
      "id":63331,
      "subject":"ASP Licensing",
      "person_name": "Mary Jarvis",
      "person_email": "mjarvis@econorob.nl",
      "agent":3,
      "messages":[
        {
          "id":123,
          "text":"if I could make the pricing attractive enough. Several of them are small, and don't ha..."
        }
      ]
    }
  ],
  "community":[
    {
      "id":83995,
      "title":"Community result"
    }
  ],
  "articles":[
    {
      "id":83995,
      "title":"Article result",
      "status":"Published",
      "content":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    },
    {
      "id":83996,
      "title":"Article result",
      "status":"Published",
      "content":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    },
    {
      "id":83997,
      "title":"Article result",
      "status":"Published",
      "content":"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    }
  ],
  "news":[
    {
      "id":83995,
      "title":"News result"
    },
    {
      "id":83996,
      "title":"News result"
    },
    {
      "id":83997,
      "title":"News result"
    }
  ],
  "downloads":[
    {
      "id":83995,
      "title":"Download result"
    }
  ],
  "admin":[
    {
      "title":"Admin result"
    },
    {
      "title":"Admin result"
    }
  ]
}
